name: Build & Release Eureka ISO

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Packer
      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer-version: latest

      # Validate Packer template
      - name: Validate Packer template
        run: packer validate packer.json

      # Build ISO using Packer
      - name: Build ISO using Packer
        run: |
          set -e
          packer build packer.json

      # Upload the ISO artifact
      - name: Upload ISO Artifact
        uses: actions/upload-artifact@ecc5516821087666a672c0d280a0084ea6d9aafd
        with:
          name: eureka-iso
          path: output-eureka-ai-os/  # Ensure this matches the output_directory in packer.json

      # Cleanup workspace to save runner space
      - name: Cleanup Workspace
        run: rm -rf output-eureka-ai-os/*

      # Optional: Notify completion
      - name: Notify Completion
        if: success()
        run: echo "ISO build and upload completed successfully!"

      # Add a failure notification step (optional)
      - name: Failure Notification
        if: failure()
        run: echo "ISO build failed. Check logs for details."