name: Build & Release Eureka ISO

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer-version: latest

      - name: Validate Packer template
        run: packer validate packer.json

      - name: Build ISO using Packer
        run: packer build packer.json

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v3
        with:
          name: eureka-iso
          path: output-eureka-ai-os/  # Ensure this matches the output_directory in packer.json