name: Build & Release Eureka ISO

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Packer
      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer-version: latest

      # Cache Packer dependencies
      - name: Cache Packer
        uses: actions/cache@v3
        with:
          path: ~/.packer
          key: ${{ runner.os }}-packer-${{ hashFiles('**/packer.json') }}
          restore-keys: |
            ${{ runner.os }}-packer-

      # Validate the Packer template
      - name: Validate Packer template
        run: packer validate packer.json

      # Build ISO using Packer
      - name: Build ISO using Packer
        run: |
          set -e
          packer build packer.json

      # Verify the ISO artifact
      - name: Verify ISO artifact
        run: |
          if [ ! -f "output-eureka-ai-os/iso-file.iso" ]; then
            echo "ISO file not found!"
            exit 1
          fi

      # Upload the ISO artifact
      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v3
        with:
          name: eureka-iso
          path: output-eureka-ai-os/

      # Cleanup workspace to save runner space
      - name: Cleanup Workspace
        run: rm -rf output-eureka-ai-os/*

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Notify on success
      - name: Notify Completion
        if: ${{ success() }}
        run: echo "✅ ISO build and upload completed successfully!"

      # Notify on failure
      - name: Notify Failure
        if: ${{ failure() }}
        run: echo "❌ ISO build failed. Please check the logs for details."